name: Run Tagged Bot every 30 minutes
on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          
      - name: Install Python dependencies
        run: |
          pip install selenium pytest
          
      - name: Verify setup
        run: |
          google-chrome --version
          chromedriver --version
          
      - name: Run tests
        run: |
          if [ -d "tests/" ] && [ -n "$(find tests/ -name "*.py" -type f)" ]; then
            pytest tests/ -v
          else
            echo "⚠️  No tests found, skipping."
          fi
          
      - name: Run bot script
        env:
          TAGGED_EMAIL: ${{ secrets.TAGGED_EMAIL }}
          TAGGED_PASSWORD: ${{ secrets.TAGGED_PASSWORD }}
        run: python tagged_bot.py

    
