name: Run Tagged Bot every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes (UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Run bot script
        env:
          TAGGED_EMAIL: ${{ secrets.TAGGED_EMAIL }}
          TAGGED_PASSWORD: ${{ secrets.TAGGED_PASSWORD }}
        run: |
          python tagged_bot.py
