name: Run Tagged Bot every 30 minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # Every 30 minutes (UTC)
  workflow_dispatch:  # Optional: lets you run manually from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-browser
          pip install selenium

      - name: Run bot
        env:
          TAGGED_EMAIL: ${{ secrets.TAGGED_EMAIL }}
          TAGGED_PASSWORD: ${{ secrets.TAGGED_PASSWORD }}
        run: |
          python tagged_bot.py
